#! /bin/bash

if (( $# != 2 ))
then
  echo "$0: Incorrect number or arguments, please enter old suffix and new suffix only." >&2 
  exit 1
fi

old_suffix=$1
new_suffix=$2

for f in *.$old_suffix
do
    new_name=${f%.*}.$new_suffix
if [[ -e $new_name ]]
then
    echo "$0: That file name already exists. Dont override!" >&2
else
    mv $f $new_name
fi
done

if [[ $? != 0 ]]
then
  echo "$0: The file was not renamed." >&2
fi
